/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

//// ------------Stagging----------------

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:1ff175df-e129-4ff7-8cc7-195f44b535e2",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_HuxOQEBi1",
    "aws_user_pools_web_client_id": "488qjp8upqv75jhg849a6l22gj",
    "oauth": {
        "domain": "nct.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "openid",
            "profile"
        ],
        "redirectSignIn": "https://localhost:4200/",
        "redirectSignOut": "https://localhost:4200/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME",
        "FAMILY_NAME"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_user_files_s3_bucket": "saasappadministration-storage-agy00784831-staging",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint_stg_honeycomb_ledger": "https://stg-honeycomb-ledger.elifcs.com/graphql",
    "aws_appsync_graphqlEndpoint_nominalAccount": "https://bzsk6nh4pnaprafs4e2junaj74.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_graphqlEndpoint_stg_honeycomb_hierarchy": "https://stg-honeycomb-hierarchy.elifcs.com/graphql",
    "aws_appsync_graphqlEndpoint_stg_honeycomb_administration": "https://stg-honeycomb-administration.elifcs.com/graphql",
    "aws_appsync_graphqlEndpoint_stg_honeycomb_cmsform": "https://stg-honeycomb-cmsforms.elifcs.com/graphql",
    "aws_appsync_graphqlEndpoint_stg_honeycomb_administration_permission": "https://tst-honeycomb-administration.elifcs.com/graphql",
    "aws_appsync_graphqlEndpoint_stg_honeycomb_sequence_generator": "https://stg-honeycomb-sequence-number.elifcs.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AWS_LAMBDA",
    "aws_appsync_apiKey": "da2-b7igb3sylrgntbfoe5ophdmtyu"
};



//// -------------Production-------------

// const awsmobile = {
//     "aws_project_region": "ap-south-1",
//     "aws_cognito_identity_pool_id": "ap-south-1:9b57e597-2a69-4137-a07b-d85ffd3fb42f",
//     "aws_cognito_region": "ap-south-1",
//     "aws_user_pools_id": "ap-south-1_cgal43pVS",
//     "aws_user_pools_web_client_id": "541trgn6bpjp04d0nbcn2j5vg2",
//     "oauth": {
//         "domain": "saasnctprd.auth.ap-south-1.amazoncognito.com",
//         "scope": [
//             "aws.cognito.signin.user.admin",
//             "openid",
//             "profile"
//         ],
//         "redirectSignIn": "https://localhost:4200/",
//         "redirectSignOut": "https://localhost:4200/",
//         "responseType": "token"
//     },
//     "federationTarget": "COGNITO_USER_POOLS",
//     "aws_cognito_username_attributes": [
//         "PHONE_NUMBER"
//     ],
//     "aws_cognito_social_providers": [],
//     "aws_cognito_signup_attributes": [
//         "NAME",
//         "FAMILY_NAME"
//     ],
//     "aws_cognito_mfa_configuration": "OPTIONAL",
//     "aws_cognito_mfa_types": [
//         "SMS"
//     ],
//     "aws_cognito_password_protection_settings": {
//         "passwordPolicyMinLength": 6,
//         "passwordPolicyCharacters": []
//     },
//     "aws_cognito_verification_mechanisms": [
//         "PHONE_NUMBER"
//     ],
//     "aws_user_files_s3_bucket": "honeycombsaasnct852-amplify-prd-storage52028-staging",
//     "aws_user_files_s3_bucket_region": "ap-south-1",
//     "aws_appsync_graphqlEndpoint": "https://n2jxcbb6kjcatjvv23wvfiqsne.appsync-api.ap-south-1.amazonaws.com/graphql",
//     "aws_appsync_graphqlEndpoint_stg_honeycomb_ledger": "https://stg-honeycomb-ledger.elifcs.com/graphql",
//     "aws_appsync_graphqlEndpoint_stg_honeycomb_hierarchy": "https://stg-honeycomb-hierarchy.elifcs.com/graphql",
//     "aws_appsync_graphqlEndpoint_stg_honeycomb_administration": "https://stg-honeycomb-administration.elifcs.com/graphql",
//     "aws_appsync_graphqlEndpoint_stg_honeycomb_cmsform": "https://stg-honeycomb-cmsforms.elifcs.com/graphql",
//     "aws_appsync_graphqlEndpoint_stg_honeycomb_administration_permission": "https://tst-honeycomb-administration.elifcs.com/graphql",
//     "aws_appsync_graphqlEndpoint_stg_honeycomb_sequence_generator": "https://stg-honeycomb-sequence-number.elifcs.com/graphql",
//     "aws_appsync_region": "ap-south-1",
//     "aws_appsync_authenticationType": "AWS_LAMBDA",
//     "aws_appsync_apiKey": "da2-b7igb3sylrgntbfoe5ophdmtyu",
// };


export default awsmobile;
